module.exports.PT_SUCCESS = 0
module.exports.PT_ERROR_AUTH_NOT_EXIST_USER = 100
module.exports.PT_ERROR_AUTH_INCORRECT_PASSWORD = 101
module.exports.PT_ERROR_AUTH_INVALID_PARAMETER = 102
module.exports.PT_ERROR_AUTH_DUPLICATE_USERID = 103
module.exports.PT_ERROR_AUTH_PASSWORD_MISSMATCH = 104
module.exports.PT_ERROR_AUTH_SERVER_ERROR = 109